### ISSUE TITLE
version for vis2

### ISSUE THREAD

**Issue by h07d0q** [Kollos2k/ioBroker.vis-shelly#7]
Is a version for vis2 planned?
can you please add some info about the usage?

**Comment by Kollos2k** [comment]
Hello... the adapter ist still in alpha mode. I have many Ideas for the future of the adapter. It is also planed to bring the Adapter to Vis2. Because the Future is in this VIS.
I'm updating the readme the next few days.

**Comment by Kollos2k** [comment]
A version for vis-2 is in work and will become an release soon.

https://github.com/Kollos2k/ioBroker.vis-2-shelly
